[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/"
  to = "/landing.html"
  status = 301
  force = true

[[redirects]]
  from = "/index.html"
  to = "/index.html"
  status = 200
  force = true
